# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

import os
from pathlib import Path

# GPU builds ship `wgpu_native.dll` next to the compiled extension. On Windows,
# add the package directory to the DLL search path so it resolves when the
# extension loads (belt-and-suspenders: the loader also searches the module's own
# directory). No-op on a CPU-only build (no DLL present) or non-Windows.
if os.name == "nt":
    _pkg_dir = Path(__file__).resolve().parent.parent  # the `aion` package dir
    if any(_pkg_dir.glob("*.dll")):
        try:
            os.add_dll_directory(str(_pkg_dir))
        except (OSError, AttributeError):  # pragma: no cover
            pass

try:
    # Compiled extension generated by cffi (API mode).
    from .._aion_cffi import ffi, lib
except ImportError as e:  # pragma: no cover
    raise ImportError(
        "Failed to import the compiled Aion extension module. "
        "This usually means the native extension was not built/installed for your Python."
    ) from e

__all__ = ["ffi", "lib"]
