# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

try:
    # Compiled extension generated by cffi (API mode).
    from .._aion_cffi import ffi, lib
except ImportError as e:  # pragma: no cover
    raise ImportError(
        "Failed to import the compiled Aion extension module. "
        "This usually means the native extension was not built/installed for your Python."
    ) from e

__all__ = ["ffi", "lib"]
