# SPDX-License-Identifier: Apache-2.0
from __future__ import annotations

from typing import Any, Protocol


class CData(Protocol):
    """Opaque CFFI cdata handle (pointer/array/struct/etc).

    cffi structs/unions are dynamically fielded, so attribute access
    (`spec.op`, `attr.matmul.alpha`, ...) and indexing are modeled as `Any`.
    """

    def __getitem__(self, index: int) -> Any: ...
    def __setitem__(self, index: int, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...


class FFI(Protocol):
    """Subset of `cffi.FFI` used by these bindings."""

    NULL: CData

    def new(self, cdecl: str, init: Any = ...) -> CData: ...
    def string(self, cdata: CData) -> bytes: ...
    def from_buffer(self, cdecl: str, python_buffer: Any) -> CData: ...


ffi: FFI


class Lib(Protocol):
    # Version / diagnostics
    def aion_version_major(self) -> int: ...
    def aion_version_minor(self) -> int: ...
    def aion_version_patch(self) -> int: ...

    def aion_status_string(self, status: int) -> CData: ...

    def aion_context_last_error_message(
        self,
        ctx: CData,
        buf: CData,
        cap: int,
        out_len: CData,
    ) -> int: ...

    # Context
    def aion_context_create_cpu(self, thread_count: int, out_ctx: CData) -> int: ...
    def aion_context_create(
        self,
        thread_count: int,
        gpus: CData,
        gpu_count: int,
        out_ctx: CData,
    ) -> int: ...
    def aion_context_destroy(self, ctx: CData) -> None: ...

    # Tensors
    def aion_tensor_create_empty(
        self,
        ctx: CData,
        dtype: int,
        rank: int,
        shape: CData,
        out_tensor: CData,
    ) -> int: ...

    def aion_tensor_create(
        self,
        ctx: CData,
        dtype: int,
        rank: int,
        shape: CData,
        values: CData,
        values_len: int,
        out_tensor: CData,
    ) -> int: ...

    def aion_tensor_create_empty_tiled(
        self,
        ctx: CData,
        dtype: int,
        rank: int,
        shape: CData,
        tile_size: CData,
        out_tensor: CData,
    ) -> int: ...

    def aion_tensor_destroy(self, t: CData) -> None: ...
    def aion_tensor_to(self, t: CData, kind: int, index: int) -> int: ...
    def aion_tensor_device(self, t: CData, out_kind: CData, out_index: CData) -> int: ...
    def aion_tensor_dtype(self, t: CData) -> int: ...
    def aion_tensor_rank(self, t: CData) -> int: ...
    def aion_tensor_shape(self, t: CData, out_dims: CData, out_rank: int) -> int: ...

    def aion_tensor_read(
        self,
        t: CData,
        dtype: int,
        out_values: CData,
        out_len: int,
    ) -> int: ...

    def aion_tensor_write(
        self,
        t: CData,
        dtype: int,
        values: CData,
        values_len: int,
    ) -> int: ...

    def aion_tensor_read_scalar(self, t: CData, dtype: int, out_value: CData) -> int: ...

    # Loaded model runtime
    def aion_loaded_model_load_path(self, ctx: CData, path: CData, opts: CData, out_model: CData) -> int: ...
    def aion_loaded_model_load_path_absolute(self, ctx: CData, absolute_path: CData, opts: CData, out_model: CData) -> int: ...
    def aion_loaded_model_destroy(self, m: CData) -> None: ...

    def aion_loaded_model_input_count(self, m: CData) -> int: ...
    def aion_loaded_model_output_count(self, m: CData) -> int: ...

    def aion_loaded_model_input_name(
        self,
        m: CData,
        index: int,
        buf: CData,
        cap: int,
        out_len: CData,
    ) -> int: ...

    def aion_loaded_model_output_name(
        self,
        m: CData,
        index: int,
        buf: CData,
        cap: int,
        out_len: CData,
    ) -> int: ...

    def aion_loaded_model_input_dtype(self, m: CData, index: int, out_dtype: CData) -> int: ...
    def aion_loaded_model_input_rank(self, m: CData, index: int, out_rank: CData) -> int: ...
    def aion_loaded_model_output_dtype(self, m: CData, index: int, out_dtype: CData) -> int: ...
    def aion_loaded_model_output_rank(self, m: CData, index: int, out_rank: CData) -> int: ...

    def aion_loaded_model_bind_input(self, m: CData, name: CData, tensor: CData) -> int: ...
    def aion_loaded_model_run(self, m: CData) -> int: ...
    def aion_loaded_model_reset_state(self, m: CData) -> int: ...
    def aion_loaded_model_set_state_input_policy(self, m: CData, name: CData, kind: int, initial_capacity_tokens: int, growth_numerator: int, growth_denominator: int, max_capacity_tokens: int, ring_window_tokens: int) -> int: ...
    def aion_loaded_model_output_tensor(self, m: CData, name: CData, out_tensor: CData) -> int: ...
    def aion_loaded_model_position(self, m: CData, out_tokens: CData) -> int: ...
    def aion_loaded_model_set_position(self, m: CData, tokens: int) -> int: ...
    def aion_loaded_model_output_is_state(self, m: CData, index: int, out_is_state: CData) -> int: ...

    # Model authoring (Builder)
    def aion_builder_create(self, ctx: CData, out_builder: CData) -> int: ...
    def aion_builder_destroy(self, b: CData) -> None: ...
    def aion_builder_input(self, b: CData, dtype: int, rank: int, shape: CData, out_value: CData) -> int: ...
    def aion_builder_param(self, b: CData, tensor: CData, out_value: CData) -> int: ...
    def aion_builder_name(self, b: CData, value: int, name: CData) -> int: ...
    def aion_builder_value_rank(self, b: CData, value: int, out_rank: CData) -> int: ...
    def aion_builder_value_shape(self, b: CData, value: int, out_dims: CData, out_rank: int) -> int: ...
    def aion_builder_value_dtype(self, b: CData, value: int, out_dtype: CData) -> int: ...
    def aion_builder_op(self, b: CData, spec: CData, out_value: CData) -> int: ...
    def aion_builder_begin_region(self, b: CData) -> int: ...
    def aion_builder_end_region(self, b: CData, outputs: CData, outputs_len: int, out_region: CData) -> int: ...
    def aion_builder_if(self, b: CData, cond: int, then_region: int, else_region: int, out_value: CData) -> int: ...
    def aion_builder_loop(
        self,
        b: CData,
        carried: CData,
        carried_len: int,
        body_region: int,
        trip: int,
        cond_carry: int,
        has_cond_carry: int,
        check_before: int,
        out_values: CData,
    ) -> int: ...
    def aion_builder_mark_output(self, b: CData, value: int, name: CData) -> int: ...
    def aion_builder_add_output_alias(self, b: CData, input_value: int, output_value: int) -> int: ...
    def aion_builder_add_input_role(
        self,
        b: CData,
        value: int,
        kind: int,
        axis: int,
        has_axis: int,
        capacity_symbol: CData,
        zero_init: int,
        allow_growable: int,
        allow_ring: int,
    ) -> int: ...
    def aion_builder_add_dim_symbol(self, b: CData, value: int, axis: int, name: CData) -> int: ...
    def aion_builder_add_metadata(self, b: CData, key: CData, value: CData) -> int: ...
    def aion_builder_compile(self, b: CData, device_kind: int, device_index: int, out_model: CData) -> int: ...
    def aion_builder_export_path(self, b: CData, path: CData) -> int: ...
    def aion_builder_export_path_absolute(self, b: CData, path: CData) -> int: ...

    def aion_tensor_quantize(
        self,
        ctx: CData,
        dtype: int,
        rank: int,
        shape: CData,
        quant_axis: int,
        values: CData,
        values_len: int,
        out_tensor: CData,
    ) -> int: ...
    def aion_tensor_create_quant(
        self,
        ctx: CData,
        dtype: int,
        rank: int,
        shape: CData,
        quant_axis: int,
        packed: CData,
        packed_len: int,
        out_tensor: CData,
    ) -> int: ...


lib: Lib
